#theme: jekyll-theme-minimal
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Climate Change Impacts to the Western States Endurance Race Course

description: An interactive map showing the ongoing effects of climate change in the Sierra Nevada foothills. Explore the map to learn how to engage and protect the trails we love. 
#background: "#fafafa"
#logo: you can upload a jpg to the git repo and call it here i.e. image.jpg 
#You can also add a logo from an image URL, as below
#logo: https://www.lawschool.cornell.edu/_cs_apps/pt_photo_gallery/uploads/mainphotogallery/fullsizeimage/Photogallery_Ithacapage_8.png

